package ch.usi.inf.sa4.sphinx.service;

import ch.usi.inf.sa4.sphinx.model.Room;
import ch.usi.inf.sa4.sphinx.model.User;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;


/*
 * Service layer of the application, the various Storage follows the CRUD principle
 */
@Service
public final class UserService {
//    @SuppressWarnings("SpringJavaAutowiringInspection")
    @Autowired
    private  UserStorage userStorage;
    @Autowired
    private  RoomStorage roomService;

    //Will be used to check that each room belongs to a single user
    private static final HashMap<String, String> roomToUser = new HashMap<>();


    /**
     *
     */
    //Used with spring injection can't be instantiated directly
    private UserService() {
    }


    /**
     * @param username the username
     * @return Returns the User with the given name if present in the storage
     */
    public User get(final String username){
        return userStorage.get(username);
    }


    public User getByMail(final String email){
        return userStorage.getByEmail(email);
    }


    /**
     * Deletes the user with the given Username from storage
     * @param username username of the user to delete
     */
    public  void delete(final String username) {
        userStorage.delete(username);
    }


    /**
     * Saves the given User in storage
     * @param user the User to save
     * @return true if success else false
     */
    public  boolean insert(final User user) {
        return userStorage.insert(user) == null;
    }

    /**
     * Updates the given user, the username is used to find the User and the given User to update its fields
     * @param username  the username of the User to update
     * @param user the User with updated fields
     * @return true if successful update else false
     */
    public boolean update(final String username, final User user){
        User oldUser = userStorage.get(username);
        if(oldUser != null){
            //Must be done manually to prevent corruption of list of owned rooms //EX: a roomId could be added to
            //User but not actually have a matching Id in the Storage. To prevent this we only update the list of
            //owned Rooms of a User in Storage from addRoom and removeRoom
            oldUser.setUsername(user.getUsername());
            oldUser.setEmail(user.getEmail());
            oldUser.setFullname(user.getFullname());
            oldUser.setPassword(user.getPassword());
            return  userStorage.update(username, oldUser);
        }
        return false;
    }


    /**
     * Adds the given room to the User, notice that both will be saved in Storage. The id of the room is generated by
     * the storage
     * @param username username of the User
     * @param room the Room to be added to the User
     * @return true if success else false
     */
    public boolean addRoom(final String username, final Room room) {
        final User user = userStorage.get(username);
        if (user == null) {
            return false;
        }

        var roomId = roomService.insert(room);
        if (roomId == null) {
            return false;
        }

        user.addRoom(roomId);
        return userStorage.update(username, user);
    }


    /**
     * @param username username of the given User
     * @return Id of the Device(s) belonging to a given User
     */
    public List<String> getDevices(final String username) {
        var devices = new ArrayList<String>();
        final User user = userStorage.get(username);

        if (user != null) {
            var roomIds = user.getRooms();
            for(var roomId: roomIds){
                var r = roomService.get(roomId);
                devices.addAll(r.getDevices());
            }
        }
        return devices;
    }


}
