image: maven

stages:
    - build
    - test
    - package
    - deploy

maven-build:
    stage: build
    script:
        - mvn clean
        - mvn compile

maven-test:
    stage: test
    script:
        - mvn test

maven-package:
    stage: package
    script:
        - mvn package
    artifacts:
        paths: [target/sphinx-backend.jar]

docker-build:
    stage: deploy
    image: docker:19.03.1
    variables:
        DOCKER_TLS_CERTDIR: ""
    services:
        - docker:19.03.1-dind
    tags: [dind]
    before_script:
        - docker login -u $DOCKER_USER -p $DOCKER_PSW       
    script:
        - docker build ./ -t $DOCKER_USER/sa4-sphinx:backend
        - docker push $DOCKER_USER/sa4-sphinx:backend