image: maven:latest

stages:
    - build
    - test
    - package
    - deploy

maven-build:
    stage: build
    script:
        - mvn clean
        - mvn compile

maven-test:
    stage: test
    script:
        - mvn test

maven-package:
    stage: package
    script:
        - mvn package
    artifacts:
        paths: [target/]

docker-build:
    stage: deploy
    image: docker    
    tags: [dind]
    script:
        - docker build ./ -t sa4-sphinx