image: maven:3-jdk-13

# Cache compiled project across all branches and jobs
cache:
    key: backend-cache
    paths:
        - target/

stages:
    - build
    - package
    - analysis
    - deploy

maven-build:
    stage: build
    script:
        - mvn compile
        - mvn test

maven-package:
    only: [dev, master]
    stage: package
    script:
        - mvn package -DskipTests
    artifacts:
        paths: [target/sphinx-backend.jar]

sonarqube:
    stage: analysis
    only:
        - dev
    script:
        - mvn -X -e --batch-mode verify sonar:sonar -Dsonar.verbose=true -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_LOGIN -Dsonar.projectKey=$CI_PROJECT_PATH_SLUG -Dsonar.projectName=$CI_PROJECT_PATH_SLUG  -Dsonar.scm.disabled=True -Dsonar.java.binaries=./target/classes/ -Dsonar.coverage.jacoco.xmlReportPaths=./target/site/jacoco/jacoco.xml

docker-build:
    only: [dev, master]
    stage: deploy
    image: docker
    variables:
        DOCKER_DRIVER: overlay2
    services:
        - docker:dind
    tags: [dind]
    before_script:
        - docker login -u $DOCKER_USER -p $DOCKER_PSW
    script:
        - docker build ./ -t $DOCKER_USER/sa4-sphinx-backend:latest
        - docker push $DOCKER_USER/sa4-sphinx-backend:latest

docker-build-tags:
    only: [tags]
    stage: deploy
    image: docker
    variables:
        DOCKER_DRIVER: overlay2
    services:
        - docker:dind
    tags: [dind]
    before_script:
        - docker login -u $DOCKER_USER -p $DOCKER_PSW
    script:
        - docker build ./ -t $DOCKER_USER/sa4-sphinx-backend:$CI_COMMIT_REF_NAME
        - docker push $DOCKER_USER/sa4-sphinx-backend:$CI_COMMIT_REF_NAME
