image: maven:3-jdk-13

stages:
    - build
    - test
    - package
    - deploy

maven-build:
    stage: build
    script:
        - mvn clean
        - mvn compile

maven-test:
    stage: test
    script:
        - mvn test

maven-package:
    stage: package
    script:
        - mvn package -DskipTests
    artifacts:
        paths: [target/sphinx-backend.jar]

docker-build:
    only: [dev, master]
    stage: deploy
    image: docker
    variables:
        DOCKER_DRIVER: overlay2
    services:
        - docker:dind
    tags: [dind]
    before_script:
        - docker login -u $DOCKER_USER -p $DOCKER_PSW       
    script:
        - docker build ./ -t $DOCKER_USER/sa4-sphinx-backend:latest
        - docker push $DOCKER_USER/sa4-sphinx-backend:latest