stages:
    - build
    - test
    - docker-test

maven-build:
    stage: build
    script:
        - mvn clean
        - mvn compile

maven-test:
    stage: test
    script:
        - mvn test

docker-build:
    stage: docker-test
    script:
        - docker build ./